version: '3'
services:
  launchapi:
    environment:
    - NASA_KEY="DONOTFORGET"
    image: launchapi:latest
    ports:
      - "8010:8010"
  nasaapi:
    environment:
    - NASA_KEY="DONOTFORGET"
    image: nasaapi:latest
    ports:
      - "8011:8011"
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cfg/nginx:/etc/nginx/conf.d
      - ./cfg/certbot/conf:/etc/letsencrypt
      - ./cfg/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - launchapi
      - nasaapi
  certbot:
    image: certbot/certbot
    volumes:
      - ./cfg/certbot/conf:/etc/letsencrypt
      - ./cfg/certbot/www:/var/www/certbot
      - ./log:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
